### ISSUE TITLE
lv1 코드리뷰

### ISSUE THREAD

**Issue by haechanlee96** [Bebeqwer/blogfirst#1]
각 api 가 설계원칙에 맞춰서 잘 짜여져 있습니다
 비밀번호에 대한 체크도 잘 되어 있습니다
 
 
   public Long deletePosting(Long id,PostingRequestDto requestDto){
        Posting posting = findPosting(id);
        if(posting.getPassword().equals(requestDto.getPassword())){
            postingRepository.delete(posting);

        }else{
            throw new IllegalArgumentException("비밀번호가 다릅니다");
        }
        return 1L;
    }
    리턴값이 불리안으로 명확하면 더 좋았을 것 같습니다!
    
    
    test 부분에 대한 코드가 없습니다

**Comment by Bebeqwer** [comment]
감사합니다
